/* auto-generated by NAPI-RS */
/* eslint-disable */
/** File-aware bridge used by Node integrations that need Rust registry resolution. */
export declare function compileFileJson(request: string, projectDir: string, offline?: boolean | undefined | null): string

/** Stable N-API bridge. Both parameters and result use the shared JSON protocol. */
export declare function compileJson(request: string): string

export declare function engineVersion(): string
