import { describe, expect, it } from "vitest";
import { TamlLexer } from "../src/lexer/lexer.js";
import { TamlParser } from "../src/parser/parser.js";
import { TamlTypeChecker } from "../src/checker/checker.js";
import { check, compile, analyzeFile, compileFile, parseAST } from "../src/compiler.js";
import { importDocument } from "../src/cli/import.js";
import { readFileSync } from "node:fs";

const valid = `interface DatabaseConfig:
  host: String
  port: Int(min: 1024, max: 65535)
  environment: "production" | "staging"
  retries?: Int = 3
component BaseService:
  replicas: 3
component "payment-api" extends BaseService implements DatabaseConfig:
  host: "db.internal.net"
  port: 5432
  environment: "production"
`;
describe("TypeYAML compiler", () => {
  it("lexes indentation and parsing tokens", () => {
    const tokens = new TamlLexer(valid).tokenize();
    expect(tokens.some(token => token.type === "INDENT")).toBe(true);
    expect(tokens.some(token => token.type === "DEDENT")).toBe(true);
    expect(TamlParser.fromSource(valid).parse().body).toHaveLength(3);
  });
  it("reports numeric constraint violations", () => {
    const program = TamlParser.fromSource(valid.replace("port: 5432", "port: 80")).parse();
    const result = new TamlTypeChecker().check(program);
    expect(result.valid).toBe(false);
    expect(result.diagnostics[0].formatted).toContain("below constraint min (1024)");
  });
  it("expands inherited component values", () => {
    const result = new TamlTypeChecker().check(TamlParser.fromSource(valid).parse());
    expect(result.valid).toBe(true);
    expect(result.components.find(component => component.name === "payment-api")?.values.replicas).toBe(3);
  });
  it("reports missing required interface values", () => {
    const result = new TamlTypeChecker().check(TamlParser.fromSource(valid.replace('  host: "db.internal.net"\n', "")).parse());
    expect(result.diagnostics[0].formatted).toContain("Property 'host' is required");
  });
  it("transpiles valid source to standard YAML", () => {
    const output = compile(valid).find(result => result.name === "payment-api")?.output;
    expect(output).toContain("# Generated by typeYAML");
    expect(output).toContain("replicas: 3");
    expect(output).toContain("port: 5432");
  });
  it("loads standard-library imports and emits source maps", async () => {
    const checked = await analyzeFile("examples/k8s-deployment.taml");
    expect(checked.valid).toBe(true);
    const output = await compileFile("examples/k8s-deployment.taml");
    expect(output[0].sourceMap.mappings.find(mapping => mapping.key === "image")?.sourceLine).toBe(5);
  });
  it("exposes the SDK parse, check, and compile API", async () => {
    expect(parseAST(valid).type).toBe("Program");
    expect(check(valid).errors).toEqual([]);
    await expect(compile(valid, { format: "json", component: "payment-api" })).resolves.toContain('"port": 5432');
  });
  it("imports legacy YAML into valid TypeYAML", () => {
    const imported = importDocument("name: payments\nport: 5432\nmetadata:\n  team: platform\n", "deployment.yaml");
    expect(imported).toContain("interface DeploymentSchema:");
    expect(imported).toContain("port: Int");
    expect(check(imported).valid).toBe(true);
  });
  it("matches the shared native parity fixture", async () => {
    const source = readFileSync("fixtures/native-parity/basic.taml", "utf8");
    const expected = readFileSync("fixtures/native-parity/basic.yaml", "utf8");
    await expect(compile(source, { format: "yaml", component: "api", header: false })).resolves.toBe(expected);
  });
});
