import { readFile, writeFile } from "node:fs/promises";
import { basename, extname } from "node:path";
import { parse } from "yaml";

type ImportedScalar = string | number | boolean | null;
interface InferredField { originalKey: string; key: string; type: "String" | "Int" | "Float" | "Boolean"; value: ImportedScalar; nested: boolean; }
export class TamlImportError extends Error { constructor(message: string) { super(`[TAML Import Error] ${message}`); } }
function identifier(input: string, index: number): string { const normalized = input.replace(/[^A-Za-z0-9_]/g, "_").replace(/^[^A-Za-z_]+/, ""); return normalized || `field_${index + 1}`; }
function title(input: string): string { const result = input.replace(/[^A-Za-z0-9]+/g, " ").replace(/(?:^|\s)([a-zA-Z0-9])/g, (_, character: string) => character.toUpperCase()).replace(/\s/g, ""); return result || "Imported"; }
function inferred(value: unknown, key: string, index: number): InferredField {
  const nested = typeof value === "object" && value !== null;
  const scalar: ImportedScalar = nested ? JSON.stringify(value) : value === null ? null : typeof value === "string" || typeof value === "number" || typeof value === "boolean" ? value : String(value);
  const type = typeof scalar === "boolean" ? "Boolean" : typeof scalar === "number" ? Number.isInteger(scalar) ? "Int" : "Float" : "String";
  return { originalKey: key, key: identifier(key, index), type, value: scalar, nested };
}
function literal(value: ImportedScalar): string { return value === null ? '"null"' : typeof value === "string" ? JSON.stringify(value) : String(value); }
/** Convert a legacy root YAML/JSON mapping to a valid scalar TypeYAML contract and component. */
export function importDocument(source: string, sourceName = "imported"): string {
  let document: unknown; try { document = parse(source); } catch (error) { throw new TamlImportError(error instanceof Error ? error.message : "unable to parse document"); }
  if (!document || typeof document !== "object" || Array.isArray(document)) throw new TamlImportError("the document root must be a mapping/object");
  const entries = Object.entries(document as Record<string, unknown>).map(([key, value], index) => inferred(value, key, index)); const base = title(basename(sourceName, extname(sourceName))); const schema = `${base}Schema`; const component = identifier(basename(sourceName, extname(sourceName)).toLowerCase(), 0);
  const lines = ["# Generated by taml import — review nested JSON-string fields before adopting.", `interface ${schema}:`];
  for (const field of entries) { if (field.nested) lines.push(`  # '${field.originalKey}' was nested and is retained as a JSON string.`); lines.push(`  ${field.key}: ${field.type}`); }
  lines.push("", `component \"${component}\" implements ${schema}:`); for (const field of entries) lines.push(`  ${field.key}: ${literal(field.value)}`); return lines.join("\n") + "\n";
}
export async function importFile(input: string, output: string): Promise<void> { const result = importDocument(await readFile(input, "utf8"), input); await writeFile(output, result, "utf8"); }
