use crate::{OutputFormat, SourceMapEntry, TamlValue, parser::Component};
fn yaml(value: &TamlValue) -> String {
    match value {
        TamlValue::String(value)
            if value.chars().all(|character| {
                character.is_ascii_alphanumeric() || matches!(character, '_' | '-' | '.' | '/')
            }) && !matches!(value.as_str(), "true" | "false" | "null") =>
        {
            value.clone()
        }
        TamlValue::String(value) => serde_json::to_string(value).unwrap_or_default(),
        TamlValue::Int(value) => value.to_string(),
        TamlValue::Float(value) => value.to_string(),
        TamlValue::Boolean(value) => value.to_string(),
        TamlValue::Enum(value) => serde_json::to_string(value).unwrap_or_default(),
    }
}
fn json(value: &TamlValue) -> String {
    match value {
        TamlValue::String(value) | TamlValue::Enum(value) => {
            serde_json::to_string(value).unwrap_or_default()
        }
        TamlValue::Int(value) => value.to_string(),
        TamlValue::Float(value) => value.to_string(),
        TamlValue::Boolean(value) => value.to_string(),
    }
}
pub fn emit(
    component: &Component,
    format: OutputFormat,
    header: bool,
) -> (String, Vec<SourceMapEntry>) {
    let header_lines = usize::from(header && matches!(format, OutputFormat::Yaml));
    let map = component
        .values
        .iter()
        .enumerate()
        .map(|(index, (key, (_, line, column)))| SourceMapEntry {
            generated_line: index + header_lines + 1,
            generated_column: 1,
            source_line: *line,
            source_column: *column,
            key: key.clone(),
        })
        .collect();
    let output = match format {
        OutputFormat::Yaml => {
            let mut result = if header {
                "# Generated by typeYAML native core — DO NOT EDIT DIRECTLY\n".into()
            } else {
                String::new()
            };
            for (key, (value, _, _)) in &component.values {
                result.push_str(&format!("{key}: {}\n", yaml(value)));
            }
            result
        }
        OutputFormat::Json => {
            let lines: Vec<String> = component
                .values
                .iter()
                .map(|(key, (value, _, _))| {
                    format!(
                        "  {}: {}",
                        serde_json::to_string(key).unwrap_or_default(),
                        json(value)
                    )
                })
                .collect();
            format!("{{\n{}\n}}\n", lines.join(",\n"))
        }
    };
    (output, map)
}
