import { rm } from "node:fs/promises";

// `dist` is exclusively generated by the build and is recreated immediately after this step.
await rm(new URL("../dist/", import.meta.url), { recursive: true, force: true });
