import { stringify } from "yaml";
import type { ComponentNode } from "../parser/ast.js";
export interface EmitOptions { header?: boolean; version?: string; }
export class YamlEmitter {
  emit(component: ComponentNode, options: EmitOptions = {}): string { const output = stringify(component.values); return options.header === false ? output : `# Generated by typeYAML (🦣) — Typed. Structured. Human. v${options.version ?? "1.0.0"} - DO NOT EDIT DIRECTLY\n${output}`; }
}
